import { EDOCITEMTYPE, IDocFileHeader, IDocFileContent, IDocFileCover, IDocFileTableOfContents } from "@frosttroll/projecttoolmodels";

export const PROJECTPLAN_TEMPLATE_DEFAULT_FI: IDocFileContent[] = [
	{
		type: EDOCITEMTYPE.COVER,
		title: "Projektin nimi tähän",
		subtitle: "Projektisuunnitelma",
	} as IDocFileCover,
	{
		type: EDOCITEMTYPE.TABLEOFCONTENTS,
		maxLevel: 3,
	} as IDocFileTableOfContents,

	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Johdanto" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Dokumentin tarkoitus" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Projektin yleiskuvaus" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Laajuus ja tavoitteet" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Sidosryhmäkartoitus" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Projektin hallintomalli" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Hallintorakenne" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Päätöksentekoprosessi" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Eskalointikäytännöt" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Muutostenhallinta ja muutospyynnöt" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Roolit ja vastuut" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Asiakasorganisaation roolit" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Toimittajan / kehitystiimin roolit" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "RACI-matriisi (vastuunjakotaulukko)" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Projektin toteutustapa ja menetelmät" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Toimitusmalli (esim. Scrum, Kanban, hybridi)" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Projektin vaiheet ja virstanpylväät" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Iteraatioiden / sprinttien rakenne" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Laadunvarmistuksen toimintatavat" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Viestintäjohtaminen" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Viestintäsuunnitelma" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Kokousrytmi (dailyt, katselmukset, ohjausryhmät)" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Raportointikäytännöt (tilanneraportit, KPI:t, koontinäytöt)" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Viestintä- ja yhteistyövälineet" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Riski- ja ongelmanhallinta" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Riskien tunnistaminen ja arviointi" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Riskienhallintastrategiat" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Ongelmakirjaus ja ratkaisuprosessi" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Laajuudenhallinta" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Vaatimusten dokumentointi" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Backlogin hallinta" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Priorisointikäytännöt" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Hyväksymiskriteerit ja hyväksyntäprosessi" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Aikataulu- ja resurssisuunnittelu" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Projektin aikataulu / yleinen etenemissuunnitelma" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Resurssisuunnitelma" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Kapasiteetin ja kuormituksen hallinta" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Budjetti- ja kustannushallinta" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Budjettirakenne" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Kustannusten seuranta ja raportointi" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Laskutusmalli (T&M, kiinteähintainen, hybridi)" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Politiikat ja standardit" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Toimintaperiaatteet ja yhteistyöpolitiikat" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Tietoturva- ja tietosuojakäytännöt (ei-tekninen yleiskuva)" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Noudatettavat määräykset ja vaatimukset" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Dokumentointikäytännöt" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Laadun- ja hyväksynnänhallinta" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Testausvastuut (ei-tekninen näkökulma)" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Katselmointi- ja hyväksymisprosessit" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Valmiuden määritelmä / hyväksymiskriteerit" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Toimitettavat artefaktit" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Projektin toimituslista" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Toimitus- ja luovutusprosessi" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Muutos- ja julkaisunhallinta" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Muutospyyntöjen käsittelyprosessi" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Julkaisusuunnittelu" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Julkaisujen aikataulut ja hyväksynnät" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Koulutus ja osaamisen siirto" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Koulutussuunnitelma" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Käyttöönoton jälkeinen osaamisen siirto" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Dokumentaation luovutus" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Projektin jälkitoimet" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Ylläpito- ja tukimalli" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Opit ja palautteet" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Projektin päättäminen" } as IDocFileHeader,
];
