import { EDOCITEMTYPE, IDocFileContent, IDocFileCover, IDocFileTableOfContents, IDocFileHeader } from "@frosttroll/projecttoolmodels";

export const PROJECTPLAN_TEMPLATE_DEFAULT_EN: IDocFileContent[] = [
	{ type: EDOCITEMTYPE.COVER, title: "Project title here" } as IDocFileCover,
	{ type: EDOCITEMTYPE.TABLEOFCONTENTS, maxLevel: 3 } as IDocFileTableOfContents,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Introduction" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Purpose of This Document" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Project Overview" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Scope and Objectives" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Stakeholder Overview" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Project Governance" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Governance Structure" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Decision-Making Process" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Escalation Paths" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Change Control & Change Requests" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Roles and Responsibilities" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Client-Side Roles" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Vendor/Development Team Roles" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "RACI Matrix (Responsibility Assignment)" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Project Approach & Methodology" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Delivery Method (e.g., Scrum, Kanban, Hybrid)" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Project Phases & Milestones", targetingKey: "phases" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Iteration/Sprint Structure" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Quality Assurance Approach" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Communication Management" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Communication Plan" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Meeting Cadence (stand-ups, reviews, steering meetings)" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Reporting Structure (status reports, KPIs, dashboards)" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Collaboration Tools & Channels" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Risk & Issue Management" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Risk Identification & Assessment" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Mitigation Strategies" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Issue Tracking & Resolution Process" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Scope Management" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Requirements Documentation" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Backlog Management" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Prioritization Process" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Acceptance Criteria & Sign-Off" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Time & Resource Planning" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Project Schedule / High-Level Timeline" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Resource Plan" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Workload & Capacity Management" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Budget & Cost Management" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Budget Structure" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Cost Tracking & Reporting" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Billing Model (T&M, fixed price, hybrid)" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Policies & Standards" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Code of Conduct & Collaboration Policies" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Security & Privacy Policies (non-technical overview)" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Compliance Requirements" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Documentation Standards" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Quality & Acceptance Management" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Testing Responsibilities (non-technical)" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Review & Approval Processes" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Definition of Done / Acceptance Criteria" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Deliverables" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Project Deliverables List" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Delivery & Handover Procedure" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Change & Release Management" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Change Request Workflow" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Release Planning" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Deployment Windows & Approvals" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Training & Knowledge Transfer" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Training Plan" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Handover to Operations" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Documentation Handover" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 1, text: "Post-Project Activities" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Maintenance & Support Model" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Lessons Learned" } as IDocFileHeader,
	{ type: EDOCITEMTYPE.HEADER, level: 2, text: "Project Closure" } as IDocFileHeader,
];
