export var ETECHCATEGORY;
(function (ETECHCATEGORY) {
    ETECHCATEGORY["LANGUAGE"] = "Programming Language";
    ETECHCATEGORY["FRAMEWORK"] = "Framework";
    ETECHCATEGORY["SERVICE"] = "Service";
    ETECHCATEGORY["LIBRARY"] = "Library";
    ETECHCATEGORY["DATABASE"] = "Database";
    ETECHCATEGORY["TOOL"] = "Tool";
    ETECHCATEGORY["PLATFORM"] = "Platform";
    ETECHCATEGORY["OTHER"] = "Other";
})(ETECHCATEGORY || (ETECHCATEGORY = {}));
export var ETECHAPPLICATIONLAYER;
(function (ETECHAPPLICATIONLAYER) {
    ETECHAPPLICATIONLAYER["FRONTEND"] = "Frontend";
    ETECHAPPLICATIONLAYER["BACKEND"] = "Backend";
    ETECHAPPLICATIONLAYER["DATABASE"] = "Database";
    ETECHAPPLICATIONLAYER["INFRA"] = "Infrastructure";
    ETECHAPPLICATIONLAYER["NETWORK"] = "Network";
    ETECHAPPLICATIONLAYER["SECURITY"] = "Security";
    ETECHAPPLICATIONLAYER["NONE"] = "None";
    ETECHAPPLICATIONLAYER["OTHER"] = "Other";
})(ETECHAPPLICATIONLAYER || (ETECHAPPLICATIONLAYER = {}));
//# sourceMappingURL=eTechType.js.map