/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIndexRouteImport } from './routes/project/index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as ProjectTechstackRouteImport } from './routes/project/techstack'
import { Route as ProjectSummarytableRouteImport } from './routes/project/summarytable'
import { Route as ProjectSettingsRouteImport } from './routes/project/settings'
import { Route as ProjectResourcesRouteImport } from './routes/project/resources'
import { Route as ProjectProjectchartsRouteImport } from './routes/project/projectcharts'
import { Route as ProjectPricingRouteImport } from './routes/project/pricing'
import { Route as ProjectPhasesRouteImport } from './routes/project/phases'
import { Route as ProjectListprojectsRouteImport } from './routes/project/listprojects'
import { Route as ProjectDashboardRouteImport } from './routes/project/dashboard'
import { Route as DataTechnologiesRouteImport } from './routes/data/technologies'
import { Route as DataRolesRouteImport } from './routes/data/roles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectTechstackRoute = ProjectTechstackRouteImport.update({
  id: '/project/techstack',
  path: '/project/techstack',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSummarytableRoute = ProjectSummarytableRouteImport.update({
  id: '/project/summarytable',
  path: '/project/summarytable',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSettingsRoute = ProjectSettingsRouteImport.update({
  id: '/project/settings',
  path: '/project/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectResourcesRoute = ProjectResourcesRouteImport.update({
  id: '/project/resources',
  path: '/project/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectchartsRoute = ProjectProjectchartsRouteImport.update({
  id: '/project/projectcharts',
  path: '/project/projectcharts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectPricingRoute = ProjectPricingRouteImport.update({
  id: '/project/pricing',
  path: '/project/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectPhasesRoute = ProjectPhasesRouteImport.update({
  id: '/project/phases',
  path: '/project/phases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectListprojectsRoute = ProjectListprojectsRouteImport.update({
  id: '/project/listprojects',
  path: '/project/listprojects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectDashboardRoute = ProjectDashboardRouteImport.update({
  id: '/project/dashboard',
  path: '/project/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTechnologiesRoute = DataTechnologiesRouteImport.update({
  id: '/data/technologies',
  path: '/data/technologies',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRolesRoute = DataRolesRouteImport.update({
  id: '/data/roles',
  path: '/data/roles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data/roles': typeof DataRolesRoute
  '/data/technologies': typeof DataTechnologiesRoute
  '/project/dashboard': typeof ProjectDashboardRoute
  '/project/listprojects': typeof ProjectListprojectsRoute
  '/project/phases': typeof ProjectPhasesRoute
  '/project/pricing': typeof ProjectPricingRoute
  '/project/projectcharts': typeof ProjectProjectchartsRoute
  '/project/resources': typeof ProjectResourcesRoute
  '/project/settings': typeof ProjectSettingsRoute
  '/project/summarytable': typeof ProjectSummarytableRoute
  '/project/techstack': typeof ProjectTechstackRoute
  '/data': typeof DataIndexRoute
  '/project': typeof ProjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data/roles': typeof DataRolesRoute
  '/data/technologies': typeof DataTechnologiesRoute
  '/project/dashboard': typeof ProjectDashboardRoute
  '/project/listprojects': typeof ProjectListprojectsRoute
  '/project/phases': typeof ProjectPhasesRoute
  '/project/pricing': typeof ProjectPricingRoute
  '/project/projectcharts': typeof ProjectProjectchartsRoute
  '/project/resources': typeof ProjectResourcesRoute
  '/project/settings': typeof ProjectSettingsRoute
  '/project/summarytable': typeof ProjectSummarytableRoute
  '/project/techstack': typeof ProjectTechstackRoute
  '/data': typeof DataIndexRoute
  '/project': typeof ProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data/roles': typeof DataRolesRoute
  '/data/technologies': typeof DataTechnologiesRoute
  '/project/dashboard': typeof ProjectDashboardRoute
  '/project/listprojects': typeof ProjectListprojectsRoute
  '/project/phases': typeof ProjectPhasesRoute
  '/project/pricing': typeof ProjectPricingRoute
  '/project/projectcharts': typeof ProjectProjectchartsRoute
  '/project/resources': typeof ProjectResourcesRoute
  '/project/settings': typeof ProjectSettingsRoute
  '/project/summarytable': typeof ProjectSummarytableRoute
  '/project/techstack': typeof ProjectTechstackRoute
  '/data/': typeof DataIndexRoute
  '/project/': typeof ProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data/roles'
    | '/data/technologies'
    | '/project/dashboard'
    | '/project/listprojects'
    | '/project/phases'
    | '/project/pricing'
    | '/project/projectcharts'
    | '/project/resources'
    | '/project/settings'
    | '/project/summarytable'
    | '/project/techstack'
    | '/data'
    | '/project'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data/roles'
    | '/data/technologies'
    | '/project/dashboard'
    | '/project/listprojects'
    | '/project/phases'
    | '/project/pricing'
    | '/project/projectcharts'
    | '/project/resources'
    | '/project/settings'
    | '/project/summarytable'
    | '/project/techstack'
    | '/data'
    | '/project'
  id:
    | '__root__'
    | '/'
    | '/data/roles'
    | '/data/technologies'
    | '/project/dashboard'
    | '/project/listprojects'
    | '/project/phases'
    | '/project/pricing'
    | '/project/projectcharts'
    | '/project/resources'
    | '/project/settings'
    | '/project/summarytable'
    | '/project/techstack'
    | '/data/'
    | '/project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRolesRoute: typeof DataRolesRoute
  DataTechnologiesRoute: typeof DataTechnologiesRoute
  ProjectDashboardRoute: typeof ProjectDashboardRoute
  ProjectListprojectsRoute: typeof ProjectListprojectsRoute
  ProjectPhasesRoute: typeof ProjectPhasesRoute
  ProjectPricingRoute: typeof ProjectPricingRoute
  ProjectProjectchartsRoute: typeof ProjectProjectchartsRoute
  ProjectResourcesRoute: typeof ProjectResourcesRoute
  ProjectSettingsRoute: typeof ProjectSettingsRoute
  ProjectSummarytableRoute: typeof ProjectSummarytableRoute
  ProjectTechstackRoute: typeof ProjectTechstackRoute
  DataIndexRoute: typeof DataIndexRoute
  ProjectIndexRoute: typeof ProjectIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/': {
      id: '/project/'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/techstack': {
      id: '/project/techstack'
      path: '/project/techstack'
      fullPath: '/project/techstack'
      preLoaderRoute: typeof ProjectTechstackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/summarytable': {
      id: '/project/summarytable'
      path: '/project/summarytable'
      fullPath: '/project/summarytable'
      preLoaderRoute: typeof ProjectSummarytableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/settings': {
      id: '/project/settings'
      path: '/project/settings'
      fullPath: '/project/settings'
      preLoaderRoute: typeof ProjectSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/resources': {
      id: '/project/resources'
      path: '/project/resources'
      fullPath: '/project/resources'
      preLoaderRoute: typeof ProjectResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/projectcharts': {
      id: '/project/projectcharts'
      path: '/project/projectcharts'
      fullPath: '/project/projectcharts'
      preLoaderRoute: typeof ProjectProjectchartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/pricing': {
      id: '/project/pricing'
      path: '/project/pricing'
      fullPath: '/project/pricing'
      preLoaderRoute: typeof ProjectPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/phases': {
      id: '/project/phases'
      path: '/project/phases'
      fullPath: '/project/phases'
      preLoaderRoute: typeof ProjectPhasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/listprojects': {
      id: '/project/listprojects'
      path: '/project/listprojects'
      fullPath: '/project/listprojects'
      preLoaderRoute: typeof ProjectListprojectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/dashboard': {
      id: '/project/dashboard'
      path: '/project/dashboard'
      fullPath: '/project/dashboard'
      preLoaderRoute: typeof ProjectDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/technologies': {
      id: '/data/technologies'
      path: '/data/technologies'
      fullPath: '/data/technologies'
      preLoaderRoute: typeof DataTechnologiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/roles': {
      id: '/data/roles'
      path: '/data/roles'
      fullPath: '/data/roles'
      preLoaderRoute: typeof DataRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRolesRoute: DataRolesRoute,
  DataTechnologiesRoute: DataTechnologiesRoute,
  ProjectDashboardRoute: ProjectDashboardRoute,
  ProjectListprojectsRoute: ProjectListprojectsRoute,
  ProjectPhasesRoute: ProjectPhasesRoute,
  ProjectPricingRoute: ProjectPricingRoute,
  ProjectProjectchartsRoute: ProjectProjectchartsRoute,
  ProjectResourcesRoute: ProjectResourcesRoute,
  ProjectSettingsRoute: ProjectSettingsRoute,
  ProjectSummarytableRoute: ProjectSummarytableRoute,
  ProjectTechstackRoute: ProjectTechstackRoute,
  DataIndexRoute: DataIndexRoute,
  ProjectIndexRoute: ProjectIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
