/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIndexRouteImport } from './routes/project/index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as ProjectTechnologyRouteImport } from './routes/project/technology'
import { Route as ProjectSettingsRouteImport } from './routes/project/settings'
import { Route as ProjectResourcesRouteImport } from './routes/project/resources'
import { Route as ProjectPricingRouteImport } from './routes/project/pricing'
import { Route as ProjectPhasesRouteImport } from './routes/project/phases'
import { Route as ProjectDashboardRouteImport } from './routes/project/dashboard'
import { Route as DataRolesRouteImport } from './routes/data/roles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectTechnologyRoute = ProjectTechnologyRouteImport.update({
  id: '/project/technology',
  path: '/project/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSettingsRoute = ProjectSettingsRouteImport.update({
  id: '/project/settings',
  path: '/project/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectResourcesRoute = ProjectResourcesRouteImport.update({
  id: '/project/resources',
  path: '/project/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectPricingRoute = ProjectPricingRouteImport.update({
  id: '/project/pricing',
  path: '/project/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectPhasesRoute = ProjectPhasesRouteImport.update({
  id: '/project/phases',
  path: '/project/phases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectDashboardRoute = ProjectDashboardRouteImport.update({
  id: '/project/dashboard',
  path: '/project/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRolesRoute = DataRolesRouteImport.update({
  id: '/data/roles',
  path: '/data/roles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data/roles': typeof DataRolesRoute
  '/project/dashboard': typeof ProjectDashboardRoute
  '/project/phases': typeof ProjectPhasesRoute
  '/project/pricing': typeof ProjectPricingRoute
  '/project/resources': typeof ProjectResourcesRoute
  '/project/settings': typeof ProjectSettingsRoute
  '/project/technology': typeof ProjectTechnologyRoute
  '/data': typeof DataIndexRoute
  '/project': typeof ProjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data/roles': typeof DataRolesRoute
  '/project/dashboard': typeof ProjectDashboardRoute
  '/project/phases': typeof ProjectPhasesRoute
  '/project/pricing': typeof ProjectPricingRoute
  '/project/resources': typeof ProjectResourcesRoute
  '/project/settings': typeof ProjectSettingsRoute
  '/project/technology': typeof ProjectTechnologyRoute
  '/data': typeof DataIndexRoute
  '/project': typeof ProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data/roles': typeof DataRolesRoute
  '/project/dashboard': typeof ProjectDashboardRoute
  '/project/phases': typeof ProjectPhasesRoute
  '/project/pricing': typeof ProjectPricingRoute
  '/project/resources': typeof ProjectResourcesRoute
  '/project/settings': typeof ProjectSettingsRoute
  '/project/technology': typeof ProjectTechnologyRoute
  '/data/': typeof DataIndexRoute
  '/project/': typeof ProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data/roles'
    | '/project/dashboard'
    | '/project/phases'
    | '/project/pricing'
    | '/project/resources'
    | '/project/settings'
    | '/project/technology'
    | '/data'
    | '/project'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data/roles'
    | '/project/dashboard'
    | '/project/phases'
    | '/project/pricing'
    | '/project/resources'
    | '/project/settings'
    | '/project/technology'
    | '/data'
    | '/project'
  id:
    | '__root__'
    | '/'
    | '/data/roles'
    | '/project/dashboard'
    | '/project/phases'
    | '/project/pricing'
    | '/project/resources'
    | '/project/settings'
    | '/project/technology'
    | '/data/'
    | '/project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRolesRoute: typeof DataRolesRoute
  ProjectDashboardRoute: typeof ProjectDashboardRoute
  ProjectPhasesRoute: typeof ProjectPhasesRoute
  ProjectPricingRoute: typeof ProjectPricingRoute
  ProjectResourcesRoute: typeof ProjectResourcesRoute
  ProjectSettingsRoute: typeof ProjectSettingsRoute
  ProjectTechnologyRoute: typeof ProjectTechnologyRoute
  DataIndexRoute: typeof DataIndexRoute
  ProjectIndexRoute: typeof ProjectIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/': {
      id: '/project/'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/technology': {
      id: '/project/technology'
      path: '/project/technology'
      fullPath: '/project/technology'
      preLoaderRoute: typeof ProjectTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/settings': {
      id: '/project/settings'
      path: '/project/settings'
      fullPath: '/project/settings'
      preLoaderRoute: typeof ProjectSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/resources': {
      id: '/project/resources'
      path: '/project/resources'
      fullPath: '/project/resources'
      preLoaderRoute: typeof ProjectResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/pricing': {
      id: '/project/pricing'
      path: '/project/pricing'
      fullPath: '/project/pricing'
      preLoaderRoute: typeof ProjectPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/phases': {
      id: '/project/phases'
      path: '/project/phases'
      fullPath: '/project/phases'
      preLoaderRoute: typeof ProjectPhasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/dashboard': {
      id: '/project/dashboard'
      path: '/project/dashboard'
      fullPath: '/project/dashboard'
      preLoaderRoute: typeof ProjectDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/roles': {
      id: '/data/roles'
      path: '/data/roles'
      fullPath: '/data/roles'
      preLoaderRoute: typeof DataRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRolesRoute: DataRolesRoute,
  ProjectDashboardRoute: ProjectDashboardRoute,
  ProjectPhasesRoute: ProjectPhasesRoute,
  ProjectPricingRoute: ProjectPricingRoute,
  ProjectResourcesRoute: ProjectResourcesRoute,
  ProjectSettingsRoute: ProjectSettingsRoute,
  ProjectTechnologyRoute: ProjectTechnologyRoute,
  DataIndexRoute: DataIndexRoute,
  ProjectIndexRoute: ProjectIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
