/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIndexRouteImport } from './routes/project/index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as ProjectTechstackRouteImport } from './routes/project/techstack'
import { Route as ProjectSummarytableRouteImport } from './routes/project/summarytable'
import { Route as ProjectSettingsRouteImport } from './routes/project/settings'
import { Route as ProjectResourcesRouteImport } from './routes/project/resources'
import { Route as ProjectProjectplanRouteImport } from './routes/project/projectplan'
import { Route as ProjectProjectchartsRouteImport } from './routes/project/projectcharts'
import { Route as ProjectPricingRouteImport } from './routes/project/pricing'
import { Route as ProjectPhasesRouteImport } from './routes/project/phases'
import { Route as ProjectListprojectsRouteImport } from './routes/project/listprojects'
import { Route as ProjectDashboardRouteImport } from './routes/project/dashboard'
import { Route as DataRolesRouteImport } from './routes/data/roles'
import { Route as DataTextsIndexRouteImport } from './routes/data/texts/index'
import { Route as DataTechnologyIndexRouteImport } from './routes/data/technology/index'
import { Route as DataTextsNewRouteImport } from './routes/data/texts/new'
import { Route as DataTechnologyNewRouteImport } from './routes/data/technology/new'
import { Route as DataTextsEditGuidRouteImport } from './routes/data/texts/edit.$guid'
import { Route as DataTechnologyEditGuidRouteImport } from './routes/data/technology/edit.$guid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectTechstackRoute = ProjectTechstackRouteImport.update({
  id: '/project/techstack',
  path: '/project/techstack',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSummarytableRoute = ProjectSummarytableRouteImport.update({
  id: '/project/summarytable',
  path: '/project/summarytable',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSettingsRoute = ProjectSettingsRouteImport.update({
  id: '/project/settings',
  path: '/project/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectResourcesRoute = ProjectResourcesRouteImport.update({
  id: '/project/resources',
  path: '/project/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectplanRoute = ProjectProjectplanRouteImport.update({
  id: '/project/projectplan',
  path: '/project/projectplan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectchartsRoute = ProjectProjectchartsRouteImport.update({
  id: '/project/projectcharts',
  path: '/project/projectcharts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectPricingRoute = ProjectPricingRouteImport.update({
  id: '/project/pricing',
  path: '/project/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectPhasesRoute = ProjectPhasesRouteImport.update({
  id: '/project/phases',
  path: '/project/phases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectListprojectsRoute = ProjectListprojectsRouteImport.update({
  id: '/project/listprojects',
  path: '/project/listprojects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectDashboardRoute = ProjectDashboardRouteImport.update({
  id: '/project/dashboard',
  path: '/project/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRolesRoute = DataRolesRouteImport.update({
  id: '/data/roles',
  path: '/data/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTextsIndexRoute = DataTextsIndexRouteImport.update({
  id: '/data/texts/',
  path: '/data/texts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTechnologyIndexRoute = DataTechnologyIndexRouteImport.update({
  id: '/data/technology/',
  path: '/data/technology/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTextsNewRoute = DataTextsNewRouteImport.update({
  id: '/data/texts/new',
  path: '/data/texts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTechnologyNewRoute = DataTechnologyNewRouteImport.update({
  id: '/data/technology/new',
  path: '/data/technology/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTextsEditGuidRoute = DataTextsEditGuidRouteImport.update({
  id: '/data/texts/edit/$guid',
  path: '/data/texts/edit/$guid',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTechnologyEditGuidRoute = DataTechnologyEditGuidRouteImport.update({
  id: '/data/technology/edit/$guid',
  path: '/data/technology/edit/$guid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data/roles': typeof DataRolesRoute
  '/project/dashboard': typeof ProjectDashboardRoute
  '/project/listprojects': typeof ProjectListprojectsRoute
  '/project/phases': typeof ProjectPhasesRoute
  '/project/pricing': typeof ProjectPricingRoute
  '/project/projectcharts': typeof ProjectProjectchartsRoute
  '/project/projectplan': typeof ProjectProjectplanRoute
  '/project/resources': typeof ProjectResourcesRoute
  '/project/settings': typeof ProjectSettingsRoute
  '/project/summarytable': typeof ProjectSummarytableRoute
  '/project/techstack': typeof ProjectTechstackRoute
  '/data': typeof DataIndexRoute
  '/project': typeof ProjectIndexRoute
  '/data/technology/new': typeof DataTechnologyNewRoute
  '/data/texts/new': typeof DataTextsNewRoute
  '/data/technology': typeof DataTechnologyIndexRoute
  '/data/texts': typeof DataTextsIndexRoute
  '/data/technology/edit/$guid': typeof DataTechnologyEditGuidRoute
  '/data/texts/edit/$guid': typeof DataTextsEditGuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data/roles': typeof DataRolesRoute
  '/project/dashboard': typeof ProjectDashboardRoute
  '/project/listprojects': typeof ProjectListprojectsRoute
  '/project/phases': typeof ProjectPhasesRoute
  '/project/pricing': typeof ProjectPricingRoute
  '/project/projectcharts': typeof ProjectProjectchartsRoute
  '/project/projectplan': typeof ProjectProjectplanRoute
  '/project/resources': typeof ProjectResourcesRoute
  '/project/settings': typeof ProjectSettingsRoute
  '/project/summarytable': typeof ProjectSummarytableRoute
  '/project/techstack': typeof ProjectTechstackRoute
  '/data': typeof DataIndexRoute
  '/project': typeof ProjectIndexRoute
  '/data/technology/new': typeof DataTechnologyNewRoute
  '/data/texts/new': typeof DataTextsNewRoute
  '/data/technology': typeof DataTechnologyIndexRoute
  '/data/texts': typeof DataTextsIndexRoute
  '/data/technology/edit/$guid': typeof DataTechnologyEditGuidRoute
  '/data/texts/edit/$guid': typeof DataTextsEditGuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data/roles': typeof DataRolesRoute
  '/project/dashboard': typeof ProjectDashboardRoute
  '/project/listprojects': typeof ProjectListprojectsRoute
  '/project/phases': typeof ProjectPhasesRoute
  '/project/pricing': typeof ProjectPricingRoute
  '/project/projectcharts': typeof ProjectProjectchartsRoute
  '/project/projectplan': typeof ProjectProjectplanRoute
  '/project/resources': typeof ProjectResourcesRoute
  '/project/settings': typeof ProjectSettingsRoute
  '/project/summarytable': typeof ProjectSummarytableRoute
  '/project/techstack': typeof ProjectTechstackRoute
  '/data/': typeof DataIndexRoute
  '/project/': typeof ProjectIndexRoute
  '/data/technology/new': typeof DataTechnologyNewRoute
  '/data/texts/new': typeof DataTextsNewRoute
  '/data/technology/': typeof DataTechnologyIndexRoute
  '/data/texts/': typeof DataTextsIndexRoute
  '/data/technology/edit/$guid': typeof DataTechnologyEditGuidRoute
  '/data/texts/edit/$guid': typeof DataTextsEditGuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data/roles'
    | '/project/dashboard'
    | '/project/listprojects'
    | '/project/phases'
    | '/project/pricing'
    | '/project/projectcharts'
    | '/project/projectplan'
    | '/project/resources'
    | '/project/settings'
    | '/project/summarytable'
    | '/project/techstack'
    | '/data'
    | '/project'
    | '/data/technology/new'
    | '/data/texts/new'
    | '/data/technology'
    | '/data/texts'
    | '/data/technology/edit/$guid'
    | '/data/texts/edit/$guid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data/roles'
    | '/project/dashboard'
    | '/project/listprojects'
    | '/project/phases'
    | '/project/pricing'
    | '/project/projectcharts'
    | '/project/projectplan'
    | '/project/resources'
    | '/project/settings'
    | '/project/summarytable'
    | '/project/techstack'
    | '/data'
    | '/project'
    | '/data/technology/new'
    | '/data/texts/new'
    | '/data/technology'
    | '/data/texts'
    | '/data/technology/edit/$guid'
    | '/data/texts/edit/$guid'
  id:
    | '__root__'
    | '/'
    | '/data/roles'
    | '/project/dashboard'
    | '/project/listprojects'
    | '/project/phases'
    | '/project/pricing'
    | '/project/projectcharts'
    | '/project/projectplan'
    | '/project/resources'
    | '/project/settings'
    | '/project/summarytable'
    | '/project/techstack'
    | '/data/'
    | '/project/'
    | '/data/technology/new'
    | '/data/texts/new'
    | '/data/technology/'
    | '/data/texts/'
    | '/data/technology/edit/$guid'
    | '/data/texts/edit/$guid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRolesRoute: typeof DataRolesRoute
  ProjectDashboardRoute: typeof ProjectDashboardRoute
  ProjectListprojectsRoute: typeof ProjectListprojectsRoute
  ProjectPhasesRoute: typeof ProjectPhasesRoute
  ProjectPricingRoute: typeof ProjectPricingRoute
  ProjectProjectchartsRoute: typeof ProjectProjectchartsRoute
  ProjectProjectplanRoute: typeof ProjectProjectplanRoute
  ProjectResourcesRoute: typeof ProjectResourcesRoute
  ProjectSettingsRoute: typeof ProjectSettingsRoute
  ProjectSummarytableRoute: typeof ProjectSummarytableRoute
  ProjectTechstackRoute: typeof ProjectTechstackRoute
  DataIndexRoute: typeof DataIndexRoute
  ProjectIndexRoute: typeof ProjectIndexRoute
  DataTechnologyNewRoute: typeof DataTechnologyNewRoute
  DataTextsNewRoute: typeof DataTextsNewRoute
  DataTechnologyIndexRoute: typeof DataTechnologyIndexRoute
  DataTextsIndexRoute: typeof DataTextsIndexRoute
  DataTechnologyEditGuidRoute: typeof DataTechnologyEditGuidRoute
  DataTextsEditGuidRoute: typeof DataTextsEditGuidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/': {
      id: '/project/'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/techstack': {
      id: '/project/techstack'
      path: '/project/techstack'
      fullPath: '/project/techstack'
      preLoaderRoute: typeof ProjectTechstackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/summarytable': {
      id: '/project/summarytable'
      path: '/project/summarytable'
      fullPath: '/project/summarytable'
      preLoaderRoute: typeof ProjectSummarytableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/settings': {
      id: '/project/settings'
      path: '/project/settings'
      fullPath: '/project/settings'
      preLoaderRoute: typeof ProjectSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/resources': {
      id: '/project/resources'
      path: '/project/resources'
      fullPath: '/project/resources'
      preLoaderRoute: typeof ProjectResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/projectplan': {
      id: '/project/projectplan'
      path: '/project/projectplan'
      fullPath: '/project/projectplan'
      preLoaderRoute: typeof ProjectProjectplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/projectcharts': {
      id: '/project/projectcharts'
      path: '/project/projectcharts'
      fullPath: '/project/projectcharts'
      preLoaderRoute: typeof ProjectProjectchartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/pricing': {
      id: '/project/pricing'
      path: '/project/pricing'
      fullPath: '/project/pricing'
      preLoaderRoute: typeof ProjectPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/phases': {
      id: '/project/phases'
      path: '/project/phases'
      fullPath: '/project/phases'
      preLoaderRoute: typeof ProjectPhasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/listprojects': {
      id: '/project/listprojects'
      path: '/project/listprojects'
      fullPath: '/project/listprojects'
      preLoaderRoute: typeof ProjectListprojectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/dashboard': {
      id: '/project/dashboard'
      path: '/project/dashboard'
      fullPath: '/project/dashboard'
      preLoaderRoute: typeof ProjectDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/roles': {
      id: '/data/roles'
      path: '/data/roles'
      fullPath: '/data/roles'
      preLoaderRoute: typeof DataRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/texts/': {
      id: '/data/texts/'
      path: '/data/texts'
      fullPath: '/data/texts'
      preLoaderRoute: typeof DataTextsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/technology/': {
      id: '/data/technology/'
      path: '/data/technology'
      fullPath: '/data/technology'
      preLoaderRoute: typeof DataTechnologyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/texts/new': {
      id: '/data/texts/new'
      path: '/data/texts/new'
      fullPath: '/data/texts/new'
      preLoaderRoute: typeof DataTextsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/technology/new': {
      id: '/data/technology/new'
      path: '/data/technology/new'
      fullPath: '/data/technology/new'
      preLoaderRoute: typeof DataTechnologyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/texts/edit/$guid': {
      id: '/data/texts/edit/$guid'
      path: '/data/texts/edit/$guid'
      fullPath: '/data/texts/edit/$guid'
      preLoaderRoute: typeof DataTextsEditGuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/technology/edit/$guid': {
      id: '/data/technology/edit/$guid'
      path: '/data/technology/edit/$guid'
      fullPath: '/data/technology/edit/$guid'
      preLoaderRoute: typeof DataTechnologyEditGuidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRolesRoute: DataRolesRoute,
  ProjectDashboardRoute: ProjectDashboardRoute,
  ProjectListprojectsRoute: ProjectListprojectsRoute,
  ProjectPhasesRoute: ProjectPhasesRoute,
  ProjectPricingRoute: ProjectPricingRoute,
  ProjectProjectchartsRoute: ProjectProjectchartsRoute,
  ProjectProjectplanRoute: ProjectProjectplanRoute,
  ProjectResourcesRoute: ProjectResourcesRoute,
  ProjectSettingsRoute: ProjectSettingsRoute,
  ProjectSummarytableRoute: ProjectSummarytableRoute,
  ProjectTechstackRoute: ProjectTechstackRoute,
  DataIndexRoute: DataIndexRoute,
  ProjectIndexRoute: ProjectIndexRoute,
  DataTechnologyNewRoute: DataTechnologyNewRoute,
  DataTextsNewRoute: DataTextsNewRoute,
  DataTechnologyIndexRoute: DataTechnologyIndexRoute,
  DataTextsIndexRoute: DataTextsIndexRoute,
  DataTechnologyEditGuidRoute: DataTechnologyEditGuidRoute,
  DataTextsEditGuidRoute: DataTextsEditGuidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
